# git
alias g='git'
# alias ga='git add'
alias gap='git add (git status | peco | sed -e "s/modified://" | sed -e "s/deleted://" | sed s/"\t"//g | sed "s/^[ \t]*//") | tr "\n" " "'
# alias gcm='git commit -m'
# alias gb='git branch'
# alias gs='git status'
# alias gp='git push'
# alias gpo='git push origin HEAD'
# alias gl='git log'
# alias gpl='git pull'
# alias gc='git checkout'
# alias gst='git stash'
# alias gstf='git stash push -u (git status | peco | sed -e "s/modified://" | sed -e "s/deleted://" | sed s/"\t"//g | sed "s/^[ \t]*//") | tr "\n" " "'
# alias gstl='git stash list'
# alias gsts='git stash save'
alias gsta='git stash apply (git stash list | peco | sed -e "s/:.*//")'
# alias gstd='git stash drop (git stash list | peco | sed -e "s/:.*//")'
alias gstp='git stash pop (git stash list | peco | sed -e "s/:.*//")'
# alias gd='git diff'
alias gdp='git diff (git status | peco | sed -e "s/modified://" | sed -e "s/deleted://" | sed s/"\t"//g | sed "s/^[ \t]*//")'
# alias gds='git diff --staged'
alias gdsp='git diff --staged (git status | peco | sed -e "s/modified://" | sed -e "s/deleted://" | sed s/"\t"//g | sed "s/^[ \t]*//")'
alias gbb='git branch -D (git branch | peco | sed "s/^[ \*]*//")'
alias gcb='git checkout (git branch | peco | sed "s/^[ \*]*//")'
# alias gfp='git ls-files | peco | tr -d "\n" | pbcopy'
alias grm='git rm --cached -r (git status | peco | sed -e "s/modified://" | sed -e "s/deleted://" | sed -e "s/new file://" | sed s/"\t"//g | sed "s/^[ \t]*//") | tr "\n" " "'
# alias gj='git jump'
# alias gm='gitmoji'
# alias gmc='gitmoji -c'
alias lg='tmux popup -E -h80% -w80% -d (pwd) "lazygit"'
alias grb='git rebase (git branch | peco | sed "s/^[ \*]*//")'
alias gmg='git merge (git branch | peco | sed "s/^[ \*]*//")'

# linux
# alias cl='clear'
alias al='alias | peco --query "$LBUFFER" | sed -e "s/^alias//" | sed -e "s/  */:/g" | sed -e "s/^://" | sed -e "s/:.*//" | tr -d "\n" | pbcopy'
alias cdp='cd (find . -maxdepth 3 -type d -not -path "*/\.git/*" | peco)'
alias rmp='rm (find . -maxdepth 3 -type f -not -path "*/\.git/*" | peco)'
alias rmrp='rm -r (find . -maxdepth 3 -type d -not -path "*/\.git/*" | peco)'
alias cat="bat --style=plain"
alias catp='bat --style=plain (find . -maxdepth 3 -type f -not -path "*/\.git/*" | peco)'
alias vip='vi (find . -maxdepth 3 -type f -not -path "*/\.git/*" | peco)'

# docker
alias d='docker'
alias dc='docker compose'
alias d-c='docker-compose'
alias drm="docker system prune"

# Fig
# alias f='fig'
# alias fr='fig run'
