include_role 'base'

include_cookbook 'tmux'
include_cookbook 'zsh'
include_cookbook 'git'
include_cookbook 'rbenv'
include_cookbook 'rosetta'
include_cookbook 'aws-sso-external'
include_cookbook 'session-manager-plugin'
include_cookbook 'fish-shell'
include_cookbook 'starship'
include_cookbook 'vim'
include_cookbook 'go'
include_cookbook 'gh'
include_cookbook 'nodenv'
