include_cookbook 'functions'

include_cookbook 'homebrew'
include_cookbook 'jq'
include_cookbook 'peco'
include_cookbook 'ghq'
include_cookbook 'tree'
include_cookbook 'tmux'
include_cookbook 'zsh'
include_cookbook 'gibo'
include_cookbook 'git'
include_cookbook 'git-lfs'
include_cookbook 'rbenv'
include_cookbook 'rosetta'
include_cookbook 'awscli'
include_cookbook 'go'
include_cookbook 'aws-sso-external'
include_cookbook 'mkr'
include_cookbook 'session-manager-plugin'
include_cookbook 'docker-desktop'
include_cookbook 'ecspresso'


darwin_app 'iterm2'
darwin_app 'figma'
darwin_app 'visual-studio-code'
