name: Dotfiles CI

on:
    push:
        branches:
        - main
    pull_request:

env:
    GH_TOKEN: ${{ github.token }}

jobs:
    macOS:
        runs-on: macos-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4
            # Runs a single command using the runners shell
            - name: Install Task
              uses: arduino/setup-task@v2
              with:
                version: 3.x
                repo-token: ${{ secrets.GITHUB_TOKEN }}
            - run: touch .tool-versions
            - uses: asdf-vm/actions/plugin-test@v3
              with:
                command: my_tool --version
            - name: Install asdf & tools
              uses: asdf-vm/actions/install@v3
            # Runs a single command using the runners shell
            - name: Set MacOS.
              run: task install
            - name: Set Up Mac Settings.
              run: task mac
