name: Dotfiles CI

on:
    push:
        branches:
        - main
    pull_request:
    schedule:
      - cron: '0 0 * * 1'

env:
    GH_TOKEN: ${{ github.token }}

jobs:
    macOS:
        runs-on: macos-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4
            # Runs a single command using the runners shell
            - name: Install Task
              uses: arduino/setup-task@v2
              with:
                version: 3.x
                repo-token: ${{ secrets.GITHUB_TOKEN }}
            # Runs a single command using the runners shell
            - name: Set MacOS.
              run: task install
            - run: task install_android
            - name: Set Up Mac Settings.
              run: task mac
