name: Dotfiles CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  macOS:
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Set MacOS.
        run: ROLE=base ./install.sh

  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: |
          apt-get update
          apt-get install -y sudo
          sudo apt-get install -y build-essential procps curl file git make
      - name: Install dotfiles
        run: ROLE=base ./install.sh
